package com.practise.dsa.strings;

import java.time.Instant;

public class CountVowelsConstants {

	public static void main(String[] args) {
		String s = "Rakeshisamanwhocanbelievedinhanumanandheneedtochangeal"
				+ "lthetimetotakecareofhanumanandbeieveindarmaruhjfhjfjfhhfhfhruijijjjfjhvhjvbhjfbhjjfdjhebhebjcjnewknejkeiuyrejeijewjekwkjknjxnxuyeuiuyruhejherjhrejherjherwjherwjhrewjhrewhjhrhejhrejhewrjhewrjhewrjhewrjhrejherjhrejhrejhrehjhrjhrjrjfhbfhbfdnfdfdjdbbcjmsdfjhsefjhjkhfjkhfejkhfjnhejnhcjncesjhnershnesrjkhnrecesthnjecsthnjecthjethjethjtechnkjechnkecthkecthntecetnestvhnjtehnbdjdfsjhdjhefuiefuifduhdfjhfdsjhdsfhfdhfdsjhdfsjhdsfjhdsfhjfhjsfhjfhkfdsndkjndjkndsfkjfdjkndsfhewiyewrerukhrjkhrsjhrejnejnhcjcjhcwsbyjegjewrhnjewrncruecjucnyncybecynbxybecgegbehbgexecygegygyregdsfhhdhjgdfghgfhjdfjhdhjhfdgfdhjhjdfhjdfjeuyyueyuewuiisjhndsbhdsgvdsgghdshjdshjdshgdsghdsgh"
				+"lthetimetotakecareofhanumanandbeieveindarmaruhjfhjfjfhhfhfhruijijjjfjhvhjvbhjfbhjjfdjhebhebjcjnewknejkeiuyrejeijewjekwkjknjxnxuyeuiuyruhejherjhrejherjherwjherwjhrewjhrewhjhrhejhrejhewrjhewrjhewrjhewrjhrejherjhrejhrejhrehjhrjhrjrjfhbfhbfdnfdfdjdbbcjmsdfjhsefjhjkhfjkhfejkhfjnhejnhcjncesjhnershnesrjkhnrecesthnjecsthnjecthjethjethjtechnkjechnkecthkecthntecetnestvhnjtehnbdjdfsjhdjhefuiefuifduhdfjhfdsjhdsfhfdhfdsjhdfsjhdsfjhdsfhjfhjsfhjfhkfdsndkjndjkndsfkjfdjkndsfhewiyewrerukhrjkhrsjhrejnejnhcjcjhcwsbyjegjewrhnjewrncruecjucnyncybecynbxybecgegbehbgexecygegygyregdsfhhdhjgdfghgfhjdfjhdhjhfdgfdhjhjdfhjdfjeuyyueyuewuiisjhndsbhdsgvdsgghdshjdshjdshgdsghdsgh"
				+"lthetimetotakecareofhanumanandbeieveindarmaruhjfhjfjfhhfhfhruijijjjfjhvhjvbhjfbhjjfdjhebhebjcjnewknejkeiuyrejeijewjekwkjknjxnxuyeuiuyruhejherjhrejherjherwjherwjhrewjhrewhjhrhejhrejhewrjhewrjhewrjhewrjhrejherjhrejhrejhrehjhrjhrjrjfhbfhbfdnfdfdjdbbcjmsdfjhsefjhjkhfjkhfejkhfjnhejnhcjncesjhnershnesrjkhnrecesthnjecsthnjecthjethjethjtechnkjechnkecthkecthntecetnestvhnjtehnbdjdfsjhdjhefuiefuifduhdfjhfdsjhdsfhfdhfdsjhdfsjhdsfjhdsfhjfhjsfhjfhkfdsndkjndjkndsfkjfdjkndsfhewiyewrerukhrjkhrsjhrejnejnhcjcjhcwsbyjegjewrhnjewrncruecjucnyncybecynbxybecgegbehbgexecygegygyregdsfhhdhjgdfghgfhjdfjhdhjhfdgfdhjhjdfhjdfjeuyyueyuewuiisjhndsbhdsgvdsgghdshjdshjdshgdsghdsgh"
				+"lthetimetotakecareofhanumanandbeieveindarmaruhjfhjfjfhhfhfhruijijjjfjhvhjvbhjfbhjjfdjhebhebjcjnewknejkeiuyrejeijewjekwkjknjxnxuyeuiuyruhejherjhrejherjherwjherwjhrewjhrewhjhrhejhrejhewrjhewrjhewrjhewrjhrejherjhrejhrejhrehjhrjhrjrjfhbfhbfdnfdfdjdbbcjmsdfjhsefjhjkhfjkhfejkhfjnhejnhcjncesjhnershnesrjkhnrecesthnjecsthnjecthjethjethjtechnkjechnkecthkecthntecetnestvhnjtehnbdjdfsjhdjhefuiefuifduhdfjhfdsjhdsfhfdhfdsjhdfsjhdsfjhdsfhjfhjsfhjfhkfdsndkjndjkndsfkjfdjkndsfhewiyewrerukhrjkhrsjhrejnejnhcjcjhcwsbyjegjewrhnjewrncruecjucnyncybecynbxybecgegbehbgexecygegygyregdsfhhdhjgdfghgfhjdfjhdhjhfdgfdhjhjdfhjdfjeuyyueyuewuiisjhndsbhdsgvdsgghdshjdshjdshgdsghdsgh"
				+"lthetimetotakecareofhanumanandbeieveindarmaruhjfhjfjfhhfhfhruijijjjfjhvhjvbhjfbhjjfdjhebhebjcjnewknejkeiuyrejeijewjekwkjknjxnxuyeuiuyruhejherjhrejherjherwjherwjhrewjhrewhjhrhejhrejhewrjhewrjhewrjhewrjhrejherjhrejhrejhrehjhrjhrjrjfhbfhbfdnfdfdjdbbcjmsdfjhsefjhjkhfjkhfejkhfjnhejnhcjncesjhnershnesrjkhnrecesthnjecsthnjecthjethjethjtechnkjechnkecthkecthntecetnestvhnjtehnbdjdfsjhdjhefuiefuifduhdfjhfdsjhdsfhfdhfdsjhdfsjhdsfjhdsfhjfhjsfhjfhkfdsndkjndjkndsfkjfdjkndsfhewiyewrerukhrjkhrsjhrejnejnhcjcjhcwsbyjegjewrhnjewrncruecjucnyncybecynbxybecgegbehbgexecygegygyregdsfhhdhjgdfghgfhjdfjhdhjhfdgfdhjhjdfhjdfjeuyyueyuewuiisjhndsbhdsgvdsgghdshjdshjdshgdsghdsgh"
				+"lthetimetotakecareofhanumanandbeieveindarmaruhjfhjfjfhhfhfhruijijjjfjhvhjvbhjfbhjjfdjhebhebjcjnewknejkeiuyrejeijewjekwkjknjxnxuyeuiuyruhejherjhrejherjherwjherwjhrewjhrewhjhrhejhrejhewrjhewrjhewrjhewrjhrejherjhrejhrejhrehjhrjhrjrjfhbfhbfdnfdfdjdbbcjmsdfjhsefjhjkhfjkhfejkhfjnhejnhcjncesjhnershnesrjkhnrecesthnjecsthnjecthjethjethjtechnkjechnkecthkecthntecetnestvhnjtehnbdjdfsjhdjhefuiefuifduhdfjhfdsjhdsfhfdhfdsjhdfsjhdsfjhdsfhjfhjsfhjfhkfdsndkjndjkndsfkjfdjkndsfhewiyewrerukhrjkhrsjhrejnejnhcjcjhcwsbyjegjewrhnjewrncruecjucnyncybecynbxybecgegbehbgexecygegygyregdsfhhdhjgdfghgfhjdfjhdhjhfdgfdhjhjdfhjdfjeuyyueyuewuiisjhndsbhdsgvdsgghdshjdshjdshgdsghdsgh"
				+"lthetimetotakecareofhanumanandbeieveindarmaruhjfhjfjfhhfhfhruijijjjfjhvhjvbhjfbhjjfdjhebhebjcjnewknejkeiuyrejeijewjekwkjknjxnxuyeuiuyruhejherjhrejherjherwjherwjhrewjhrewhjhrhejhrejhewrjhewrjhewrjhewrjhrejherjhrejhrejhrehjhrjhrjrjfhbfhbfdnfdfdjdbbcjmsdfjhsefjhjkhfjkhfejkhfjnhejnhcjncesjhnershnesrjkhnrecesthnjecsthnjecthjethjethjtechnkjechnkecthkecthntecetnestvhnjtehnbdjdfsjhdjhefuiefuifduhdfjhfdsjhdsfhfdhfdsjhdfsjhdsfjhdsfhjfhjsfhjfhkfdsndkjndjkndsfkjfdjkndsfhewiyewrerukhrjkhrsjhrejnejnhcjcjhcwsbyjegjewrhnjewrncruecjucnyncybecynbxybecgegbehbgexecygegygyregdsfhhdhjgdfghgfhjdfjhdhjhfdgfdhjhjdfhjdfjeuyyueyuewuiisjhndsbhdsgvdsgghdshjdshjdshgdsghdsgh"
				+"lthetimetotakecareofhanumanandbeieveindarmaruhjfhjfjfhhfhfhruijijjjfjhvhjvbhjfbhjjfdjhebhebjcjnewknejkeiuyrejeijewjekwkjknjxnxuyeuiuyruhejherjhrejherjherwjherwjhrewjhrewhjhrhejhrejhewrjhewrjhewrjhewrjhrejherjhrejhrejhrehjhrjhrjrjfhbfhbfdnfdfdjdbbcjmsdfjhsefjhjkhfjkhfejkhfjnhejnhcjncesjhnershnesrjkhnrecesthnjecsthnjecthjethjethjtechnkjechnkecthkecthntecetnestvhnjtehnbdjdfsjhdjhefuiefuifduhdfjhfdsjhdsfhfdhfdsjhdfsjhdsfjhdsfhjfhjsfhjfhkfdsndkjndjkndsfkjfdjkndsfhewiyewrerukhrjkhrsjhrejnejnhcjcjhcwsbyjegjewrhnjewrncruecjucnyncybecynbxybecgegbehbgexecygegygyregdsfhhdhjgdfghgfhjdfjhdhjhfdgfdhjhjdfhjdfjeuyyueyuewuiisjhndsbhdsgvdsgghdshjdshjdshgdsghdsgh"
				+"lthetimetotakecareofhanumanandbeieveindarmaruhjfhjfjfhhfhfhruijijjjfjhvhjvbhjfbhjjfdjhebhebjcjnewknejkeiuyrejeijewjekwkjknjxnxuyeuiuyruhejherjhrejherjherwjherwjhrewjhrewhjhrhejhrejhewrjhewrjhewrjhewrjhrejherjhrejhrejhrehjhrjhrjrjfhbfhbfdnfdfdjdbbcjmsdfjhsefjhjkhfjkhfejkhfjnhejnhcjncesjhnershnesrjkhnrecesthnjecsthnjecthjethjethjtechnkjechnkecthkecthntecetnestvhnjtehnbdjdfsjhdjhefuiefuifduhdfjhfdsjhdsfhfdhfdsjhdfsjhdsfjhdsfhjfhjsfhjfhkfdsndkjndjkndsfkjfdjkndsfhewiyewrerukhrjkhrsjhrejnejnhcjcjhcwsbyjegjewrhnjewrncruecjucnyncybecynbxybecgegbehbgexecygegygyregdsfhhdhjgdfghgfhjdfjhdhjhfdgfdhjhjdfhjdfjeuyyueyuewuiisjhndsbhdsgvdsgghdshjdshjdshgdsghdsgh"
				+"lthetimetotakecareofhanumanandbeieveindarmaruhjfhjfjfhhfhfhruijijjjfjhvhjvbhjfbhjjfdjhebhebjcjnewknejkeiuyrejeijewjekwkjknjxnxuyeuiuyruhejherjhrejherjherwjherwjhrewjhrewhjhrhejhrejhewrjhewrjhewrjhewrjhrejherjhrejhrejhrehjhrjhrjrjfhbfhbfdnfdfdjdbbcjmsdfjhsefjhjkhfjkhfejkhfjnhejnhcjncesjhnershnesrjkhnrecesthnjecsthnjecthjethjethjtechnkjechnkecthkecthntecetnestvhnjtehnbdjdfsjhdjhefuiefuifduhdfjhfdsjhdsfhfdhfdsjhdfsjhdsfjhdsfhjfhjsfhjfhkfdsndkjndjkndsfkjfdjkndsfhewiyewrerukhrjkhrsjhrejnejnhcjcjhcwsbyjegjewrhnjewrncruecjucnyncybecynbxybecgegbehbgexecygegygyregdsfhhdhjgdfghgfhjdfjhdhjhfdgfdhjhjdfhjdfjeuyyueyuewuiisjhndsbhdsgvdsgghdshjdshjdshgdsghdsgh"
				+"lthetimetotakecareofhanumanandbeieveindarmaruhjfhjfjfhhfhfhruijijjjfjhvhjvbhjfbhjjfdjhebhebjcjnewknejkeiuyrejeijewjekwkjknjxnxuyeuiuyruhejherjhrejherjherwjherwjhrewjhrewhjhrhejhrejhewrjhewrjhewrjhewrjhrejherjhrejhrejhrehjhrjhrjrjfhbfhbfdnfdfdjdbbcjmsdfjhsefjhjkhfjkhfejkhfjnhejnhcjncesjhnershnesrjkhnrecesthnjecsthnjecthjethjethjtechnkjechnkecthkecthntecetnestvhnjtehnbdjdfsjhdjhefuiefuifduhdfjhfdsjhdsfhfdhfdsjhdfsjhdsfjhdsfhjfhjsfhjfhkfdsndkjndjkndsfkjfdjkndsfhewiyewrerukhrjkhrsjhrejnejnhcjcjhcwsbyjegjewrhnjewrncruecjucnyncybecynbxybecgegbehbgexecygegygyregdsfhhdhjgdfghgfhjdfjhdhjhfdgfdhjhjdfhjdfjeuyyueyuewuiisjhndsbhdsgvdsgghdshjdshjdshgdsghdsgh"
				+"lthetimetotakecareofhanumanandbeieveindarmaruhjfhjfjfhhfhfhruijijjjfjhvhjvbhjfbhjjfdjhebhebjcjnewknejkeiuyrejeijewjekwkjknjxnxuyeuiuyruhejherjhrejherjherwjherwjhrewjhrewhjhrhejhrejhewrjhewrjhewrjhewrjhrejherjhrejhrejhrehjhrjhrjrjfhbfhbfdnfdfdjdbbcjmsdfjhsefjhjkhfjkhfejkhfjnhejnhcjncesjhnershnesrjkhnrecesthnjecsthnjecthjethjethjtechnkjechnkecthkecthntecetnestvhnjtehnbdjdfsjhdjhefuiefuifduhdfjhfdsjhdsfhfdhfdsjhdfsjhdsfjhdsfhjfhjsfhjfhkfdsndkjndjkndsfkjfdjkndsfhewiyewrerukhrjkhrsjhrejnejnhcjcjhcwsbyjegjewrhnjewrncruecjucnyncybecynbxybecgegbehbgexecygegygyregdsfhhdhjgdfghgfhjdfjhdhjhfdgfdhjhjdfhjdfjeuyyueyuewuiisjhndsbhdsgvdsgghdshjdshjdshgdsghdsgh"
				+"lthetimetotakecareofhanumanandbeieveindarmaruhjfhjfjfhhfhfhruijijjjfjhvhjvbhjfbhjjfdjhebhebjcjnewknejkeiuyrejeijewjekwkjknjxnxuyeuiuyruhejherjhrejherjherwjherwjhrewjhrewhjhrhejhrejhewrjhewrjhewrjhewrjhrejherjhrejhrejhrehjhrjhrjrjfhbfhbfdnfdfdjdbbcjmsdfjhsefjhjkhfjkhfejkhfjnhejnhcjncesjhnershnesrjkhnrecesthnjecsthnjecthjethjethjtechnkjechnkecthkecthntecetnestvhnjtehnbdjdfsjhdjhefuiefuifduhdfjhfdsjhdsfhfdhfdsjhdfsjhdsfjhdsfhjfhjsfhjfhkfdsndkjndjkndsfkjfdjkndsfhewiyewrerukhrjkhrsjhrejnejnhcjcjhcwsbyjegjewrhnjewrncruecjucnyncybecynbxybecgegbehbgexecygegygyregdsfhhdhjgdfghgfhjdfjhdhjhfdgfdhjhjdfhjdfjeuyyueyuewuiisjhndsbhdsgvdsgghdshjdshjdshgdsghdsgh"
				+"lthetimetotakecareofhanumanandbeieveindarmaruhjfhjfjfhhfhfhruijijjjfjhvhjvbhjfbhjjfdjhebhebjcjnewknejkeiuyrejeijewjekwkjknjxnxuyeuiuyruhejherjhrejherjherwjherwjhrewjhrewhjhrhejhrejhewrjhewrjhewrjhewrjhrejherjhrejhrejhrehjhrjhrjrjfhbfhbfdnfdfdjdbbcjmsdfjhsefjhjkhfjkhfejkhfjnhejnhcjncesjhnershnesrjkhnrecesthnjecsthnjecthjethjethjtechnkjechnkecthkecthntecetnestvhnjtehnbdjdfsjhdjhefuiefuifduhdfjhfdsjhdsfhfdhfdsjhdfsjhdsfjhdsfhjfhjsfhjfhkfdsndkjndjkndsfkjfdjkndsfhewiyewrerukhrjkhrsjhrejnejnhcjcjhcwsbyjegjewrhnjewrncruecjucnyncybecynbxybecgegbehbgexecygegygyregdsfhhdhjgdfghgfhjdfjhdhjhfdgfdhjhjdfhjdfjeuyyueyuewuiisjhndsbhdsgvdsgghdshjdshjdshgdsghdsgh"
				+"lthetimetotakecareofhanumanandbeieveindarmaruhjfhjfjfhhfhfhruijijjjfjhvhjvbhjfbhjjfdjhebhebjcjnewknejkeiuyrejeijewjekwkjknjxnxuyeuiuyruhejherjhrejherjherwjherwjhrewjhrewhjhrhejhrejhewrjhewrjhewrjhewrjhrejherjhrejhrejhrehjhrjhrjrjfhbfhbfdnfdfdjdbbcjmsdfjhsefjhjkhfjkhfejkhfjnhejnhcjncesjhnershnesrjkhnrecesthnjecsthnjecthjethjethjtechnkjechnkecthkecthntecetnestvhnjtehnbdjdfsjhdjhefuiefuifduhdfjhfdsjhdsfhfdhfdsjhdfsjhdsfjhdsfhjfhjsfhjfhkfdsndkjndjkndsfkjfdjkndsfhewiyewrerukhrjkhrsjhrejnejnhcjcjhcwsbyjegjewrhnjewrncruecjucnyncybecynbxybecgegbehbgexecygegygyregdsfhhdhjgdfghgfhjdfjhdhjhfdgfdhjhjdfhjdfjeuyyueyuewuiisjhndsbhdsgvdsgghdshjdshjdshgdsghdsgh"
				+"lthetimetotakecareofhanumanandbeieveindarmaruhjfhjfjfhhfhfhruijijjjfjhvhjvbhjfbhjjfdjhebhebjcjnewknejkeiuyrejeijewjekwkjknjxnxuyeuiuyruhejherjhrejherjherwjherwjhrewjhrewhjhrhejhrejhewrjhewrjhewrjhewrjhrejherjhrejhrejhrehjhrjhrjrjfhbfhbfdnfdfdjdbbcjmsdfjhsefjhjkhfjkhfejkhfjnhejnhcjncesjhnershnesrjkhnrecesthnjecsthnjecthjethjethjtechnkjechnkecthkecthntecetnestvhnjtehnbdjdfsjhdjhefuiefuifduhdfjhfdsjhdsfhfdhfdsjhdfsjhdsfjhdsfhjfhjsfhjfhkfdsndkjndjkndsfkjfdjkndsfhewiyewrerukhrjkhrsjhrejnejnhcjcjhcwsbyjegjewrhnjewrncruecjucnyncybecynbxybecgegbehbgexecygegygyregdsfhhdhjgdfghgfhjdfjhdhjhfdgfdhjhjdfhjdfjeuyyueyuewuiisjhndsbhdsgvdsgghdshjdshjdshgdsghdsgh";// a,e,i,o,u
		long startTime = Instant.now().toEpochMilli();
		countVowelsAndConstants(s);
		long endTime = Instant.now().toEpochMilli();
		System.out.println("Time Taken: "+ (endTime-startTime));
		long startTime2 = Instant.now().toEpochMilli();
		countVowelsAndConstantOptimized(s);
		long endTime2 = Instant.now().toEpochMilli();
		System.out.println("Time Taken 2nd: "+ (endTime2-startTime2));
	}
	
	// Count vowels and consonants
	// Time : o(n^2), Either for loop and with contains method which is slower
	public static void countVowelsAndConstants(String s){
		int constants = 0;
		int vowels = 0;
		String vowelStr = "aeiou";
		char[] charArray = s.toCharArray();
		for(int i=0;i<charArray.length;i++) {
			if(vowelStr.contains(String.valueOf(charArray[i]).toLowerCase())) {
				vowels++;
			}else {
				constants++;
			}
		}
		System.out.println("Constants: "+constants + " Vowels: "+vowels);
	}
	
	public static void countVowelsAndConstantOptimized(String s){
		
		int vowels =0;
		int constants =0;
		boolean isVowel[] = new boolean[25];
		isVowel['a' - 'a'] = true;
		isVowel['e' - 'a'] = true;
		isVowel['i' - 'a'] = true;
		isVowel['o' - 'a'] = true;
		isVowel['u' - 'a'] = true;
		
		for(char chars : s.toLowerCase().toCharArray()) {
			if(isVowel[chars - 'a']) {
				vowels++;
			}else {
				constants++;
			}
		}
		System.out.println("Consonants: " + constants + " Vowels: " + vowels);
	}
}
